# Generated by Django 4.0.4 on 2022-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='product_imgs/logonsozinho.jpg', null=True, upload_to='product_imgs/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem1',
            field=models.ImageField(blank=True, default='product_imgs/logonsozinho.jpg', null=True, upload_to='product_imgs/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem2',
            field=models.ImageField(blank=True, default='product_imgs/logonsozinho.jpg', null=True, upload_to='product_imgs/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem3',
            field=models.ImageField(blank=True, default='product_imgs/logonsozinho.jpg', null=True, upload_to='product_imgs/'),
        ),
    ]
