# Generated by Django 4.0.4 on 2022-04-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='imagem_marca',
            new_name='imagemarca',
        ),
    ]
