# Generated by Django 4.0.4 on 2022-04-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttribute',
            new_name='ProdutoAtributo',
        ),
    ]
