# Generated by Django 4.0.4 on 2022-06-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_produto_imagem_alter_produto_imagem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhopedidoitems',
            name='item',
            field=models.CharField(max_length=150),
        ),
    ]
