# Generated by Django 4.0.4 on 2022-04-25 01:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_productattribute_produtoatributo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartOrder',
            new_name='CarrinhoPedido',
        ),
        migrations.RenameModel(
            old_name='CartOrderItems',
            new_name='CarrinhoPedidoItems',
        ),
    ]
