# Generated by Django 4.0.4 on 2022-06-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carrinhopedidoitems_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregar',
            options={'verbose_name_plural': 'Entregar'},
        ),
    ]
