# Generated by Django 4.0.4 on 2022-04-25 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_cartorder_carrinhopedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='ProdutoFeedback',
        ),
    ]
