# Generated by Django 4.0.4 on 2022-04-25 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_rename_productreview_produtofeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddressBook',
            new_name='UserEnderecoLista',
        ),
    ]
