# Generated by Django 4.0.4 on 2022-04-25 02:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_rename_useraddressbook_userenderecolista'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='ListaDesejo',
        ),
    ]
