# Generated by Django 4.0.4 on 2022-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_wishlist_listadesejo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Marca',
        ),
    ]
